### PR TITLE
Added chmod perm, modal to change, api with local/ftp/sftp

### PR DESCRIPTION
**Pull request by AndreiTelteu**
I started implementing the long-requested chmod functionality. #112 

Feedback is welcomed

image

image

Progress: 

 - ✅ Save permissions for local driver - **done and tested**
 - ✅ Save for FTP - **done and tested**
 - ✅ Save for SFTP - **done and tested**
 - ✅ Read for local driver - **done and tested**
 - ✅ Read for FTP driver - **done and tested**
 - ✅ Read for SFTP driver - **done and tested**
 - ✅ Hide the permissions button when driver does not support it
 - ✅ Make a custom `FilegatorFtp` that extends the original - **done and tested**
 - ✅ Add a recursive option (all / only files / only dirs) - **done and tested**

### CODE REVIEW

**Comment by AndreiTelteu** [comment]
I finished reading permissions from ftp adapter. It's very ugly. I had to copy-paste a bunch of functions from the Ftp and AbstractFtpAdapter to make it work.

Possible future alternative better option is to create `FilegatorFtpAdapter` that extends `Adapter/Ftp` and only overwrite the `normalizeUnixObject` function. The only downside is that everyone has to switch from the original adapter to this modified one to make use of permissions. 
Any thoughts on this?

**Comment by alcalbg** [comment]
Thanks for this!

I agree, this is very awkward and ugly solution. 

I would rather have a brand new `FilegatorFtpAdapter` adapter with this functionality. Those who need this feature can look into it and make a switch.

However, the storage service needs to be adjusted first with permissions parameters and some defaults to maintain compatibility.

I also see that [flysystem](https://flysystem.thephpleague.com/docs/usage/unix-visibility/#article) has added some support for file permissions, and the upgrade of this library is already overdue.

**Comment by AndreiTelteu** [comment]
@alcalbg should we proceed with this current ugly ftp solution for now ? Only the recursive function remains to be developed for this PR to be complete.

Maybe I'll have time for a filesystem upgrade in a separate pr.

**Comment by AndreiTelteu** [comment]
> I also see that [flysystem](https://flysystem.thephpleague.com/docs/usage/unix-visibility/#article) has added some support for file permissions, and the upgrade of this library is already overdue.

Actually it still [does not expose raw permissions](https://github.com/thephpleague/flysystem/blob/be639d62a8ac69f17cac2d70d38415e3ee2cb721/src/Ftp/FtpAdapter.php#L419). When we switch to v3 we still don't know the exact permissions of a file, and we can't change them individually. Only a visibility parameter is present, the same as now on v1.

[That function](https://flysystem.thephpleague.com/docs/usage/unix-visibility/#article) only does permission matching and conversion for `visibility == public ? 0644 : 0600`.

**Comment by AndreiTelteu** [comment]
This PR it's done. I accomplished that I think it's needed

@alcalbg I am trying to run `vendor/bin/phpstan analyse ./backend` but I get errors on existing files that I didn't modify, and then it stopped (` [ERROR] Found 12 errors `)
WPAuth.php => wp_get_current_user not found... etc
Vuejs.php    => Access to an undefined property ...rs\Vuejs::$add_to_head

Do I need to install something additional for this?

**Comment by AndreiTelteu** [comment]
@alcalbg Did you have any chance to look at the final version?

**Comment by alcalbg** [comment]
No, not yet, sorry, I have other work to finish atm

**Comment by zoot** [comment]
@AndreiTelteu your additions look ideal, since I've been eyeing out FileGator, but not proceeding, because of the inability to set UNIX file permissions.

It's unclear (to me) whether or not your PR does in fact implement what your screen shot implies, or whether the visibility layer of FlySystem is blocking this. Please clarify? Thanks.

My understanding is that you've avoided the visibility abstraction and have added the ability to set real UNIX permissions. Is this accurate. Sorry, I haven't downloaded and applied your code yet.

**Comment by zoot** [comment]
Thanks for the prompt reply @AndreiTelteu and the good news :)

I'll set some time aside to apply your patch to the master branch and test with the local filesystem driver.

**Comment by jaapmarcus** [comment]
Any news regarding this PR?

Would love to see it merged...

**Comment by Nils98Ar** [comment]
@AndreiTelteu Any news on this?

**Comment by Bortus-AI** [comment]
Any news on this?

**Comment by ponasromas** [comment]
Why this is not merged?

**Comment by zoot** [comment]
@tlcd96 please review the above thread. I am neither a developer on this project, nor do I have time to contribute. Merely a possible and grateful end-user who has not yet had the time to attempt to apply the available patch for my own testing.

**Comment by AndreiTelteu** [comment]
Hi @alcalbg 
I merged with the latest version of master, and squoshed all my commit in only one.
What else is needed for this pr to be merged ?

**Comment by alcalbg** [comment]
This is now merged and released as [v7.10.0](https://github.com/filegator/filegator/releases/tag/v7.10.0)

**Pull request merged**
